version: 0.2

phases:
  build:
    commands:
      - npm ci
      - npm run build-prod

artifacts:
  files:
    - appspec.yml
    - scripts/beforeInstall.sh
    - scripts/afterInstall.sh
    - dist/**/*
